version: "3.7"

services: 

  #api:
  #  build:
  #    context: .
  #    dockerfile: ./src/ShoppingCart/Hosts/ShoppingCart.Api/Dockerfile
  #  ports:
  #    - 5000:80
  #  environment:
  #    - ConnectionStrings_PostgresShoppingCartDb=Server=postgres;Database=ShoppingCart;Username=postpostgressword=postpostgrest=5432
  #  depends_on:
  #    - postgres

  #pgadmin:
  #  image: dpage/pgadmin4
  #  #container_name: pgadmin
  #  restart: always
  #  ports:
  #    - "5050:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  volumes:
  #    - pgadmin-data:/var/lib/pgadmin
  #  depends_on:
  #    - postgres    

  postgres:
    image: "postgres:14-alpine" # use latest official postgres version
    restart: always
    environment: # configure postgres 
        - POSTGRES_USER=postgres
        - POSTGRES_DB=ShoppingCart
        - POSTGRES_PASSWORD=postgres
    ports: 
        - "5432:5432"
    volumes: # persist data even if container shuts down
        - postgres_data:/var/lib/postgresql/data/
    
volumes: # named volumes can be managed easier using docker-compose
  postgres_data:
  #pgadmin-data: